#!/usr/bin/env python3
"""Deterministic internal TRAIN/VALIDATION split of the frozen AV2
Scale-Up v2 10,000-scenario TRAIN-source dataset (PR #54,
``ad_morai_bridge_dev/config/dataset_factory/av2_motion_forecasting_adapter/
scaleup_v2_train_scenarios.manifest.json``).

This is a SECOND, independent split layer on top of the Scale-Up v2
dataset's own single-role ``scaleup_v2_train_split.json`` (which marks
all 10,000 scenarios ``role=train`` relative to the physically separate
1,000-scenario official-VAL root -- see
``tools/av2_dataset_prep/build_scaleup_v2_split_manifests.py``). That
outer split is never touched here. This module only subdivides the
10,000-scenario TRAIN pool itself into:

- 9,000 scenarios -> TRAIN (used for gradient updates)
- 1,000 scenarios -> INTERNAL VALIDATION (used ONLY for early stopping /
  checkpoint selection / KF calibration -- never for gradient updates)

The 1,000-scenario OFFICIAL AV2 VAL set (a disjoint scenario pool by AV2's
own train/val split construction, re-verified programmatically by this
module's own ``main()``) is a third, completely separate set and is never
read here.

Deliberately NOT ``av2_split.py::assign_split`` (that function enforces a
mandatory train/val/test 3-way carve-out of one scenario pool with each
bucket non-empty); this task needs exactly two buckets (train, internal
val), so the split is generated by the SAME deterministic
seeded-shuffle-of-sorted-ids discipline used everywhere else in this
project (``assign_split``, ``assign_scenarios_to_shards``) but without a
degenerate empty ``test`` requirement. ``av2_split.py`` itself is not
modified.

Produces a manifest in the SAME schema
(``av2_kalmannet_stage0_split_v1``) ``kalmannet_sequences.load_split_sequences``
already knows how to read (it always looks for ``splits["train"]``,
``splits["val"]``, ``splits["test"]``) -- ``test`` is simply an empty list
here, never populated, never read by any downstream code in this task.

A NEW fixed seed is used (``20260930``), distinct from every seed already
used anywhere in this project's AV2 history (dataset selection seeds
20260905/20260910/20260920/20260921; every prior split-generation seed
20260905/its own stage1 seed) -- chosen once, frozen, never re-rolled.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from av2_split import SPLIT_MANIFEST_SCHEMA_VERSION  # noqa: E402

INTERNAL_SPLIT_SEED = 20260930
N_TRAIN = 9000
N_INTERNAL_VAL = 1000


class InternalSplitError(RuntimeError):
    pass


def assign_internal_split(
    scenario_ids: list[str], n_train: int = N_TRAIN, n_val: int = N_INTERNAL_VAL, seed: int = INTERNAL_SPLIT_SEED,
) -> dict[str, str]:
    """Deterministic given (the *set* of scenario_ids, n_train, n_val,
    seed) -- sorts first so input traversal order never matters, then a
    seeded ``random.Random`` shuffle (never Python's process-randomized
    ``hash()``, never unseeded ``random``). Every scenario_id must be
    assigned to exactly one of {"train", "val"} -- no third bucket, no
    dropped scenario."""
    unique_sorted = sorted(set(scenario_ids))
    if len(unique_sorted) != len(scenario_ids):
        raise InternalSplitError("duplicate scenario_ids in input")
    n = len(unique_sorted)
    if n_train + n_val != n:
        raise InternalSplitError(
            f"n_train({n_train}) + n_val({n_val}) = {n_train + n_val} != scenario_count({n})"
        )
    if n_train <= 0 or n_val <= 0:
        raise InternalSplitError("n_train and n_val must both be positive")

    rng = random.Random(seed)
    shuffled = list(unique_sorted)
    rng.shuffle(shuffled)

    assignment: dict[str, str] = {}
    for sid in shuffled[:n_train]:
        assignment[sid] = "train"
    for sid in shuffled[n_train:]:
        assignment[sid] = "val"
    return assignment


def build_internal_split_manifest(
    scenario_ids: list[str], scenario_manifest_provenance: dict[str, Any],
    n_train: int = N_TRAIN, n_val: int = N_INTERNAL_VAL, seed: int = INTERNAL_SPLIT_SEED,
) -> dict[str, Any]:
    assignment = assign_internal_split(scenario_ids, n_train=n_train, n_val=n_val, seed=seed)

    by_split: dict[str, list[str]] = {"train": [], "val": [], "test": []}
    for sid, split in assignment.items():
        by_split[split].append(sid)
    for name in ("train", "val", "test"):
        by_split[name].sort()

    all_ids = by_split["train"] + by_split["val"] + by_split["test"]
    if sorted(all_ids) != sorted(set(scenario_ids)):
        raise InternalSplitError("internal split does not exactly cover the input scenario_ids")
    if len(all_ids) != len(set(all_ids)):
        raise InternalSplitError("a scenario_id appears in more than one internal-split bucket")
    if by_split["test"]:
        raise InternalSplitError("internal split must never populate the 'test' bucket")

    return {
        "schema_version": SPLIT_MANIFEST_SCHEMA_VERSION,
        "split_policy": "scenario_level_internal_train_val_of_scaleup_v2_train_pool",
        "not_av2_official_test_split": True,
        "official_av2_val_is_a_separate_physical_root_never_read_here": True,
        "config": {"n_train": n_train, "n_val": n_val, "seed": seed},
        "scenario_count": len(scenario_ids),
        "split_counts": {name: len(by_split[name]) for name in ("train", "val", "test")},
        "splits": by_split,
        "scenario_manifest_provenance": scenario_manifest_provenance,
    }


def write_manifest(manifest: dict[str, Any], path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def check_disjoint_from_official_val(internal_scenario_ids: list[str], official_val_scenario_ids: list[str]) -> int:
    """Returns the overlap count (must be 0)."""
    return len(set(internal_scenario_ids) & set(official_val_scenario_ids))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--train-scenario-manifest", type=Path, required=True,
                         help="scaleup_v2_train_scenarios.manifest.json (committed, 10,000 scenarios)")
    parser.add_argument("--official-val-scenario-manifest", type=Path, required=True,
                         help="scaleup_v2_official_val_scenarios.manifest.json (committed, 1,000 scenarios) "
                              "-- used ONLY to verify zero overlap, never read otherwise")
    parser.add_argument("--n-train", type=int, default=N_TRAIN)
    parser.add_argument("--n-val", type=int, default=N_INTERNAL_VAL)
    parser.add_argument("--seed", type=int, default=INTERNAL_SPLIT_SEED)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    train_manifest = json.loads(args.train_scenario_manifest.read_text("utf-8"))
    official_val_manifest = json.loads(args.official_val_scenario_manifest.read_text("utf-8"))
    train_scenario_ids = [s["scenario_id"] for s in train_manifest["scenarios"]]
    official_val_scenario_ids = [s["scenario_id"] for s in official_val_manifest["scenarios"]]

    manifest = build_internal_split_manifest(
        train_scenario_ids,
        scenario_manifest_provenance={
            "manifest_schema_version": train_manifest.get("manifest_schema_version"),
            "selection_seed": train_manifest.get("selection_seed"),
            "selection_pool_size": train_manifest.get("selection_pool_size"),
            "split": train_manifest.get("split"),
            "scenario_count": train_manifest.get("scenario_count"),
        },
        n_train=args.n_train, n_val=args.n_val, seed=args.seed,
    )

    overlap_internal_val_vs_official_val = check_disjoint_from_official_val(
        manifest["splits"]["val"], official_val_scenario_ids
    )
    overlap_internal_train_vs_official_val = check_disjoint_from_official_val(
        manifest["splits"]["train"], official_val_scenario_ids
    )
    if overlap_internal_val_vs_official_val != 0 or overlap_internal_train_vs_official_val != 0:
        raise InternalSplitError(
            "official AV2 VAL scenario_ids leaked into the internal TRAIN/VAL split: "
            f"train_overlap={overlap_internal_train_vs_official_val} "
            f"val_overlap={overlap_internal_val_vs_official_val}"
        )
    manifest["verified_overlap_with_official_val"] = {
        "internal_train_vs_official_val": overlap_internal_train_vs_official_val,
        "internal_val_vs_official_val": overlap_internal_val_vs_official_val,
    }

    write_manifest(manifest, args.output)
    print(json.dumps({
        "output": str(args.output),
        "split_counts": manifest["split_counts"],
        "verified_overlap_with_official_val": manifest["verified_overlap_with_official_val"],
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
