from glob import glob
import os

from setuptools import find_packages, setup


package_name = "ad_morai_bridge_dev"

setup(
    name=package_name,
    version="0.1.0",
    packages=find_packages(exclude=["test"]),
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml"]),
        (
            os.path.join("share", package_name, "launch"),
            glob("launch/*.launch.py"),
        ),
        (
            os.path.join("share", package_name, "config"),
            glob("config/*.yaml"),
        ),
        (
            # Generated by scripts/generate_morai_descriptors.py.
            os.path.join("share", package_name, "data"),
            ["data/morai_api.desc"],
        ),
    ],
    install_requires=["setuptools", "grpcio>=1.60,<2", "PyYAML>=5.4"],
    zip_safe=True,
    maintainer="Taeyeong",
    maintainer_email="taeyeong@users.noreply.github.com",
    description="Development-only MORAI UDP and gRPC to ROS 2 bridge",
    license="Apache-2.0",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "ad_morai_bridge_dev_node = ad_morai_bridge_dev.bridge.node:main",
            "ad_morai_scenario_setup = ad_morai_bridge_dev.scenarios.setup_node:main",
            "ad_morai_scenario_reset = ad_morai_bridge_dev.scenarios.reset_node:main",
            "eskf_ab_harness = ad_morai_bridge_dev.eskf_experiment.node:main",
            "ad_morai_imu_timing_eval = ad_morai_bridge_dev.imu_timing.eval:main",
            "ad_morai_actor = ad_morai_bridge_dev.actors.cli:main",
            "ad_morai_perception_bag = ad_morai_bridge_dev.perception.bag:main",
            "ad_morai_perception_mcap_audit = "
            "ad_morai_bridge_dev.perception.mcap_audit:main",
        ],
    },
)
