/**:
  ros__parameters:
    queue_capacity: 64
    publish_raw_packets: false
    extra_raw_streams:
      names: []
    grpc:
      enabled: false

    camera_bboxes:
      enabled: false
    ego_status:
      enabled: false
    objects:
      enabled: false
    lidar2d:
      enabled: false
    traffic_light_status:
      enabled: false
    intersection_status:
      enabled: false
    npc_collisions:
      enabled: false

    ego_ghost:
      enabled: false
    traffic_light:
      enabled: false
    intersection:
      enabled: false
    sensor_control:
      enabled: false
    lamp_control:
      enabled: false
    scenario_load:
      enabled: false
    save_sensor_data:
      enabled: false
    npc_ghost:
      enabled: false
    multi_ego:
      enabled: true
      target_ip: 127.0.0.1
      target_port: 7604
