/**:
  ros__parameters:
    topics:
      input: /ad/perception/lidar/deskewed
      output: /ad/perception/lidar/cropped
    base_frame: base_link
    bounds:
      min_x_m: -0.990
      max_x_m: 4.045
      min_y_m: -1.145
      max_y_m: 1.145
      min_z_m: -0.200
      max_z_m: 1.805
    transform_timeout_sec: 0.1
