localization_manager:
  ros__parameters:
    input_odometry_topic: /ad/localization/backends/gnss_imu/odometry
    canonical_odometry_topic: /ad/localization/odometry
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    publish_tf: true
